# Generated by Django 4.2.6 on 2023-11-26 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("shwe_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_category",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="image_type",
            field=models.CharField(default="horizontal", max_length=255),
        ),
    ]
