# Generated by Django 4.2.6 on 2023-11-28 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shwe_app", "0003_alter_image_image_category_alter_image_image_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image_category",
            new_name="image_orientation",
        ),
    ]
