# Generated by Django 4.2.6 on 2023-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shwe_app", "0004_rename_image_category_image_image_orientation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_description",
            field=models.TextField(blank=True),
        ),
    ]
