# Generated by Django 4.2.6 on 2023-12-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shwe_app", "0005_alter_image_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                        default=None,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
