# Generated by Django 4.2.6 on 2023-12-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shwe_app", "0006_visitorcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorcount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
